language: ruby
rvm:
- 2.0.0
- 1.9.3
notifications:
  email:
    recipients:
    - harikrishna.kanta@v2solutions.com
    - kantaharikrishna@gmail.com
install:
- gem install mysql2
- bundle install
- bundle exec rake db:create RAILS_ENV=test
- bundle exec rake db:migrate
deploy:
  provider: appfog
  email: kantaharikrishna@gmail.com
  password: aqswde1!
  app:
    master: railslover
    
